### ISSUE TITLE
Ability to set the classpath when running java

### ISSUE THREAD

**Issue by magnayn-mns** [pulumi/pulumi-java#1152]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I'm playing with pulumi with some pre-baked java code, which I can invoke in the usual fashion:

```
runtime:
  name: java
  options:
    binary: ./build/libs/scripting-host.jar 
```

Unfortunately, my code then fails because there is a dependency that doesn't live in that jarfile. I've tried building a fat-jar instead, but this fails for other reasons (as the code inside itself does some classpath manipulation and obviously gets the wrong answer).

It would be really nice to be able to specify the classpath when invoking, something like

```
runtime:
  name: java
  options:
    binary: ./build/libs/scripting-host.jar 
    classpath: ./build/distributions/scripting-host/lib/guava-31.1-jre.jar:etc:etc:etc
```

### Affected area/feature

Pulumi-java-executor
