### ISSUE TITLE
Java host seems to be passing incorrect args to components (in pulumi-deploy-executor)

### ISSUE THREAD

**Issue by automagic** [pulumi/pulumi-java#1706]
### What happened?

Component is getting `-v=3` (a Pulumi verbosity flag) instead of the passed string:

<img width="2058" alt="Image" src="https://github.com/user-attachments/assets/c851f083-619f-42d6-885a-ce6530aa30b7" />

### Example

A custom component in Java (https://github.com/pulumi-initech/pulumi-java-component-acm-dnsvalidatedcertificate) is added to the project via `pulumi package add https://github.com/pulumi-initech/pulumi-java-component-acm-dnsvalidatedcertificate@v1.0.0` and consumed in YAML:

Locally there is no issue, but in the incorrect value somehow gets passed when running in Pulumi deployments  
```
name: test
description: test
runtime: yaml
resources:
  cert:
    type: acm:index:DnsValidatedCertificate
    properties:
      domainName: ${subDomain}.${hostedZoneName}
      zoneId:
        fn::invoke:
          function: aws:route53:getZone
          arguments:
            name: ${hostedZoneName}
          return: zoneId
outputs:
  certificateArn:
    value: ${cert.certificateArn}
```

### Output of `pulumi about`

3.153.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
